oauth:
  google:
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: ${OAUTH_GOOGLE_REDIRECT}
    url:
      auth: https://accounts.google.com/o/oauth2/v2/auth
      token: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v2/userinfo

  frontend:
    landing-uri: ${OAUTH_FRONTEND_LANDING_URL}